version: '3'

volumes:
  PG_data:
  static_data:
  media_data:

services:
  db:
    image: postgres:13.0 
    container_name: foodgram-db  
    env_file: .env
    volumes:
      - PG_data:/var/lib/postgresql/data/

  backend:
    image: fedor389111/foodgram_backend
    container_name: foodgram-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_data:/app/static/
      - media_data:/app/media

  frontend:
    env_file: .env
    image: fedor389111/foodgram_frontend
    container_name: foodgram-frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.24.0-alpine
    container_name: foodgram-gateway
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/      
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    depends_on:
      - backend
